# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01727b951c6c57f367785c5e5c5762ffb5708e51a30302234bd9dba408b5aba26ffe69f5330862c474edb7dd29ce1799fa1fff37c5a9ba49231bf96b76ebbf96

test:
  secret_key_base: 4b6b41b6c15cadd04336dac0805e651f2e64de730528834bfba39e037e2e2ad5cf82bd2ae4969a278c20c1613b26dca22ee5b148837ea9b6e1068d7f8d6a802d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
